version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    labels:
      - "dependencies 📦"
      - "javascript 🟨"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies 📦"
      - "github-actions :octocat:"
    schedule:
      interval: "monthly"
