import { type INodeProperties, updateDisplayOptions } from 'n8n-workflow';
import {
	COUNTRY_CODES,
	CUSTOMER_SALES_CHANNELS,
	PARTY_TYPES,
	SALUTATIONS,
	SOCIAL_MEDIA_CODES,
} from '../shared/enum';
import { dryRunQueryParameter } from '../shared/QueryParameter';

const properties: INodeProperties[] = [
	dryRunQueryParameter,
	{
		name: 'attributes',
		displayName: 'Attributes',
		type: 'collection',
		default: {},
		placeholder: 'Add Attribute',
		options: [
			{
				name: 'addresses',
				displayName: 'Addresses',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: true,
				},
				default: {},
				placeholder: 'Add Address',
				options: [
					{
						name: 'address',
						displayName: 'Address',
						values: [
							{
								name: 'primaryAddress',
								displayName: 'Primary address',
								description: 'Whether the address is the primary address',
								type: 'boolean',
								default: false,
							},
							{
								name: 'deliveryAddress',
								displayName: 'Delivery address',
								description: 'Whether the address is a delivery address',
								type: 'boolean',
								default: false,
							},
							{
								name: 'invoiceAddress',
								displayName: 'Invoice address',
								description: 'Whether the address is an invoice address',
								type: 'boolean',
								default: false,
							},
							{
								name: 'differentCompany',
								displayName: 'Different company',
								description: 'Whether the address is a different company',
								type: 'boolean',
								default: false,
								// dont sent this to the API, it is only used to show/hide the company and company2 fields
								routing: {
									request: {},
								},
							},
							{
								name: 'company',
								displayName: 'Company',
								description: 'Company of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: 'Acme Inc.',
								displayOptions: {
									show: {
										differentCompany: [true],
									},
								},
							},
							{
								name: 'company2',
								displayName: 'Company addition',
								description: 'Company addition of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: 'Acme Inc. 2',
								displayOptions: {
									show: {
										differentCompany: [true],
									},
								},
							},
							{
								name: 'salutation',
								displayName: 'Salutation',
								description: 'Salutation of the customer',
								type: 'options',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: 'Mr.',
								options: SALUTATIONS,
							},
							{
								name: 'titleId',
								displayName: 'Title id',
								description: 'Title id of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: '12345',
							},
							{
								name: 'firstName',
								displayName: 'First Name',
								description: 'First name of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: 'John',
							},
							{
								name: 'lastName',
								displayName: 'Last Name',
								description: 'Last name of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: 'Doe',
							},
							{
								name: 'phone',
								displayName: 'Phone',
								description: 'Phone number of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: '+49 30 12345678',
							},
							{
								name: 'street1',
								displayName: 'Street',
								description: 'Street of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: 'Main Street 1',
							},
							{
								name: 'street2',
								displayName: 'Street addition',
								description: 'Second line of the street address of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: 'Main Street 2',
							},
							{
								name: 'state',
								displayName: 'State',
								description: 'State of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: 'Berlin',
							},
							{
								name: 'zipCode',
								displayName: 'Zip Code',
								description: 'Zip code of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: '12345',
							},
							{
								name: 'city',
								displayName: 'City',
								description: 'City of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: 'Berlin',
							},
							{
								name: 'countryCode',
								displayName: 'Country Code',
								description: 'Country code of the customer',
								type: 'options',
								default: '',
								options: COUNTRY_CODES,
							},
							{
								name: 'globalLocationNumber',
								displayName: 'Global location number',
								description: 'Global location number of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: '1234567890123',
							},
							{
								name: 'postOfficeBoxNumber',
								displayName: 'Post office box number',
								description: 'Post office box number of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: '12345',
							},
							{
								name: 'postOfficeBoxZipCode',
								displayName: 'Post office box zip code',
								description: 'Post office box zip code of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: '12345',
							},
							{
								name: 'postOfficeBoxCity',
								displayName: 'Post office box city',
								description: 'Post office box city of the customer',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: 'Berlin',
							},
						],
					},
				],
			},
			{
				name: 'birthDate',
				displayName: 'Birth Date',
				description: 'Birth date of the customer',
				type: 'dateTime',
				typeOptions: {
					dateOnly: true,
				},
				default: '',
				// needs to be converted to integer timestamp in milliseconds for the API
				routing: {
					send: {
						type: 'body',
						property: 'birthDate',
						value: '={{ Date.parse($value) }}',
					},
				},
			},
			{
				name: 'company',
				displayName: 'Company',
				description: 'Company name of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
				placeholder: 'Weclapp GmbH',
				routing: {
					send: {
						type: 'body',
						property: 'company',
					},
				},
			},
			{
				name: 'company2',
				displayName: 'Company additional field 2',
				description: 'Additional company field 2 of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
				placeholder: 'Weclapp GmbH',
				routing: {
					send: {
						type: 'body',
						property: 'company2',
					},
				},
			},
			{
				name: 'email',
				displayName: 'Email',
				description: 'Email address of the party',
				type: 'string',
				default: '',
				placeholder: 'john.doe@weclapp.com',
				routing: {
					send: {
						type: 'body',
						property: 'email',
					},
				},
			},
			{
				name: 'emailHome',
				displayName: 'Email Home',
				description: 'Home email address of the party',
				type: 'string',
				default: '',
				placeholder: 'john.doe@weclapp.com',
				routing: {
					send: {
						type: 'body',
						property: 'emailHome',
					},
				},
			},
			{
				name: 'fax',
				displayName: 'Fax',
				description: 'Fax number of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
				placeholder: '+49 30 12345678',
				routing: {
					send: {
						type: 'body',
						property: 'fax',
					},
				},
			},
			{
				name: 'firstName',
				displayName: 'First Name',
				description: 'First name of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
				placeholder: 'John',
				routing: {
					send: {
						type: 'body',
						property: 'firstName',
					},
				},
			},
			{
				name: 'lastName',
				displayName: 'Last Name',
				description: 'Last name of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
				placeholder: 'Doe',
				routing: {
					send: {
						type: 'body',
						property: 'lastName',
					},
				},
			},
			{
				name: 'middleName',
				displayName: 'Middle Name',
				description: 'Middle name of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
				placeholder: 'Doe',
				routing: {
					send: {
						type: 'body',
						property: 'middleName',
					},
				},
			},
			{
				name: 'mobilePhone1',
				displayName: 'Mobile Phone',
				description: 'Mobile phone number of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
				placeholder: '+49 151 12345678',
				routing: {
					send: {
						type: 'body',
						property: 'mobilePhone',
					},
				},
			},
			{
				name: 'Online accounts',
				displayName: 'Online accounts',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: true,
				},
				default: {},
				placeholder: 'Add Online Account',
				options: [
					{
						name: 'onlineAccount',
						displayName: 'Online account',
						values: [
							{
								name: 'accountType',
								displayName: 'Account Type',
								description: 'Type of the online account',
								type: 'options',
								default: '',
								options: SOCIAL_MEDIA_CODES,
							},
							{
								name: 'accountName',
								displayName: 'Account Name',
								description: 'Name of the online account',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: 'john.doe',
							},
							{
								name: 'url',
								displayName: 'Account URL',
								description: 'URL of the online account',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
								placeholder: 'https://www.facebook.com/john.doe',
							},
						],
					},
				],
			},
			{
				name: 'partyType',
				displayName: 'Party Type',
				description: 'Type of the party',
				type: 'options',
				default: '',
				options: PARTY_TYPES,
			},
			{
				name: 'personCompany',
				displayName: "Person's Company",
				description: 'Company of the person',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
				placeholder: 'Weclapp GmbH',
				routing: {
					send: {
						type: 'body',
						property: 'personCompany',
					},
				},
			},
			{
				name: 'personDepartmentId',
				displayName: "Person's Department ID",
				description: 'Department ID of the person',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'personRoleId',
				displayName: "Person's Role ID",
				description: 'Role ID of the person',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'phone',
				displayName: 'Phone',
				description: 'Phone number of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
				placeholder: '+49 30 12345678',
				routing: {
					send: {
						type: 'body',
						property: 'phone',
					},
				},
			},
			{
				name: 'primaryAddressId',
				displayName: 'Primary Address ID',
				description: 'ID of the primary address of the party',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'salutation',
				displayName: 'Salutation',
				description: 'Salutation of the party',
				type: 'options',
				default: '',
				options: SALUTATIONS,
			},
			{
				name: 'tags',
				displayName: 'Tags',
				description: 'Tags of the party',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: true,
				},
				default: '',
				placeholder: 'Add Tag',
				options: [
					{
						name: 'items',
						displayName: 'Tag',
						values: [
							{
								name: 'tag',
								displayName: 'Tag',
								description: 'Tag to add to the party',
								type: 'string',
								default: '',
							},
						],
					},
				],
				routing: {
					send: {
						type: 'body',
						property: 'tags',
						value: '={{$parameter.tags.items.map(item => item.tag)}}',
					},
				},
			},
			{
				name: 'titleId',
				displayName: 'Title ID',
				description: 'ID of the title of the party',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'website',
				displayName: 'Website',
				description: 'Website of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
				placeholder: 'https://www.weclapp.com',
			},
			{
				name: 'bankAccounts',
				displayName: 'Bank Accounts',
				description: 'Bank accounts of the party',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: true,
				},
				default: '',
				placeholder: 'Add Bank Account',
				options: [
					{
						name: 'bankAccount',
						displayName: 'Bank Account',
						values: [
							{
								name: 'accountHolder',
								displayName: 'Account Holder',
								description: 'Name of the account holder',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
							},
							{
								name: 'accountNumber',
								displayName: 'Account Number',
								description: 'Account number of the bank account',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
							},
							{
								name: 'bankCode',
								displayName: 'Bank Code',
								description: 'Bank code of the bank account',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
							},
							{
								name: 'creditInstitute',
								displayName: 'Credit Institute',
								description: 'Credit institute of the bank account',
								type: 'string',
								typeOptions: {
									maxLength: 1000,
								},
								default: '',
							},
							{
								name: 'partyId',
								displayName: 'Party ID',
								description: 'ID of the party to which the bank account belongs',
								type: 'string',
								default: '',
							},
							{
								name: 'primary',
								displayName: 'Primary',
								description:
									'Whether the bank account is the primary bank account of the party',
								type: 'boolean',
								default: false,
							},
						],
					},
				],
			},
			{
				name: 'commercialLanguageId',
				displayName: 'Commercial Language ID',
				description: 'ID of the commercial language of the party',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'commissionBlock',
				displayName: 'Commission Block',
				description: 'Whether the party is blocked for commission',
				type: 'boolean',
				default: false,
			},
			{
				name: 'commissionSalesPartners',
				displayName: 'Commission Sales Partners',
				description: 'Sales partners for commission of the party',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: true,
				},
				default: '',
				placeholder: 'Add Sales Partner',
				options: [
					{
						name: 'salesPartner',
						displayName: 'Sales Partner',
						values: [
							{
								name: 'commissionFix',
								displayName: 'Commission Fix',
								description: 'Fixed commission amount for the sales partner',
								type: 'number',
								default: 0,
							},
							{
								name: 'commissionPercentage',
								displayName: 'Commission Percentage',
								description: 'Commission percentage for the sales partner',
								type: 'number',
								default: 0,
							},
							{
								name: 'commissionType',
								displayName: 'Commission Type',
								description: 'Type of commission for the sales partner',
								type: 'options',
								default: '',
								options: [
									{
										name: 'Fix',
										value: 'FIX',
									},
									{
										name: 'Fix and Margin',
										value: 'FIX_AND_MARGIN',
									},
									{
										name: 'Fix and Revenue',
										value: 'FIX_AND_REVENUE',
									},
									{
										name: 'Margin',
										value: 'MARGIN',
									},
									{
										name: 'No Commission',
										value: 'NO_COMMISSION',
									},
									{
										name: 'Revenue',
										value: 'REVENUE',
									},
								],
							},
							{
								name: 'salesPartnerSupplierId',
								displayName: 'Sales Partner Supplier ID',
								description: 'ID of the sales partner supplier',
								type: 'string',
								default: '',
							},
						],
					},
				],
			},
			{
				name: 'companySizeId',
				displayName: 'Company Size ID',
				description: 'ID of the company size of the party',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'competitor',
				displayName: 'Competitor',
				description: 'Whether the party is a competitor',
				type: 'boolean',
				default: false,
			},
			{
				name: 'currencyId',
				displayName: 'Currency ID',
				description: 'ID of the currency of the party',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'customer',
				displayName: 'Customer',
				description: 'Whether the party is a customer',
				type: 'boolean',
				default: false,
			},
			{
				name: 'customerActive',
				displayName: 'Customer Active',
				description: 'Whether the customer is active',
				type: 'boolean',
				default: false,
			},
			{
				name: 'customerAllowDropshippingOrderCreation',
				displayName: 'Customer Allow Dropshipping Order Creation',
				description: 'Whether the customer allows dropshipping order creation',
				type: 'boolean',
				default: false,
			},
			{
				name: 'customerAmountInsured',
				displayName: 'Customer Amount Insured',
				description: 'Amount insured for the customer',
				type: 'number',
				default: 0,
			},
			{
				name: 'customerAnnualRevenue',
				displayName: 'Customer Annual Revenue',
				description: 'Annual revenue of the customer',
				type: 'number',
				default: 0,
			},
			{
				name: 'customerBlockNotice',
				displayName: 'Customer Block Notice',
				description: 'Block notice of the customer',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
			},
			{
				name: 'customerBlocked',
				displayName: 'Customer Blocked',
				description: 'Whether the customer is blocked',
				type: 'boolean',
				default: false,
			},
			{
				name: 'customerBusinessType',
				displayName: 'Customer Business Type',
				description: 'Business type of the customer',
				type: 'options',
				default: '',
				options: [
					{
						name: 'B2B',
						value: 'B2B',
					},
					{
						name: 'B2C',
						value: 'B2C',
					},
					{
						name: 'B2G',
						value: 'B2G',
					},
				],
			},
			{
				name: 'customerCategoryId',
				displayName: 'Customer Category ID',
				description: 'ID of the customer category',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'customerCreditLimit',
				displayName: 'Customer Credit Limit',
				description: 'Credit limit of the customer',
				type: 'number',
				default: 0,
			},
			{
				name: 'customerCurrentSalesStageId',
				displayName: 'Customer Current Sales Stage ID',
				description: 'ID of the current sales stage of the customer',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'customerDebtorAccountId',
				displayName: 'Customer Debtor Account ID',
				description: 'ID of the debtor account of the customer',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'customerDebtorAccountingCodeId',
				displayName: 'Customer Debtor Accounting Code ID',
				description: 'ID of the debtor accounting code of the customer',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'customerDefaultHeaderDiscount',
				displayName: 'Customer Default Header Discount',
				description: 'Default header discount of the customer',
				type: 'number',
				default: 0,
			},
			{
				name: 'customerDefaultHeaderSurcharge',
				displayName: 'Customer Default Header Surcharge',
				description: 'Default header surcharge of the customer',
				type: 'number',
				default: 0,
			},
			{
				name: 'customerDefaultShippingCarrierId',
				displayName: 'Customer Default Shipping Carrier ID',
				description: 'ID of the default shipping carrier of the customer',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'customerDefaultWarehouseId',
				displayName: 'Customer Default Warehouse ID',
				description: 'ID of the default warehouse of the customer',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'customerDeliveryBlock',
				displayName: 'Customer Delivery Block',
				description: 'Whether the customer has a delivery block',
				type: 'boolean',
				default: false,
			},
			{
				name: 'customerInsolvent',
				displayName: 'Customer Insolvent',
				description: 'Whether the customer is insolvent',
				type: 'boolean',
				default: false,
			},
			{
				name: 'customerInsured',
				displayName: 'Customer Insured',
				description: 'Whether the customer is insured',
				type: 'boolean',
				default: false,
			},
			{
				name: 'customerInternalNote',
				displayName: 'Customer Internal Note',
				description: 'Internal note of the customer',
				type: 'string',
				default: '',
			},
			{
				name: 'customerLossDescription',
				displayName: 'Customer Loss Description',
				description: 'Loss description of the customer',
				type: 'string',
				default: '',
			},
			{
				name: 'customerLossReasonId',
				displayName: 'Customer Loss Reason ID',
				description: 'ID of the loss reason of the customer',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'customerNonStandardTaxId',
				displayName: 'Customer Non Standard Tax ID',
				description: 'ID of the non-standard tax of the customer',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'customerNumber',
				displayName: 'Customer Number',
				description: 'Number of the customer',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
			},
			{
				name: 'customerNumberOld',
				displayName: 'Customer Number Old',
				description: 'Old number of the customer',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
			},
			{
				name: 'customerPaymentMethodId',
				displayName: 'Customer Payment Method ID',
				description: 'ID of the payment method of the customer',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'customerSalesChannel',
				displayName: 'Customer Sales Channel',
				description: 'Sales channel of the customer',
				type: 'options',
				default: '',
				options: CUSTOMER_SALES_CHANNELS,
			},
			{
				name: 'customerSalesOrderPaymentType',
				displayName: 'Customer Sales Order Payment Type',
				description: 'Sales order payment type of the customer',
				type: 'options',
				default: '',
				options: [
					{
						name: 'Advance Payment',
						value: 'ADVANCE_PAYMENT',
					},
					{
						name: 'Counter Sales',
						value: 'COUNTER_SALES',
					},
					{
						name: 'Part Payment',
						value: 'PART_PAYMENT',
					},
					{
						name: 'Prepayment',
						value: 'PREPAYMENT',
					},
					{
						name: 'Standard',
						value: 'STANDARD',
					},
				],
			},
			{
				name: 'customerSalesProbability',
				displayName: 'Customer Sales Probability',
				description: 'Sales probability of the customer',
				type: 'number',
				default: 0,
			},
			{
				name: 'customerSatisfaction',
				displayName: 'Customer Satisfaction',
				description: 'Satisfaction of the customer',
				type: 'options',
				default: '',
				options: [
					{
						name: 'Neutral',
						value: 'NEUTRAL',
					},
					{
						name: 'Satisfied',
						value: 'SATISFIED',
					},
					{
						name: 'Unsatisfied',
						value: 'UNSATISFIED',
					},
				],
			},
			{
				name: 'customerShipmentMethodId',
				displayName: 'Customer Shipment Method ID',
				description: 'ID of the shipment method of the customer',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'customerSupplierNumber',
				displayName: 'Customer Supplier Number',
				description: 'Supplier number of the customer',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
			},
			{
				name: 'customerTermOfPaymentId',
				displayName: 'Customer Term Of Payment ID',
				description: 'ID of the term of payment of the customer',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'customerUseCustomsTariffNumber',
				displayName: 'Customer Use Customs Tariff Number',
				description: 'Whether the customer uses customs tariff numbers',
				type: 'boolean',
				default: false,
			},
			{
				name: 'deliveryEmailAddressesId',
				displayName: 'Delivery Email Addresses ID',
				description: 'ID of the delivery email addresses',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'description',
				displayName: 'Description',
				description: 'Description of the party',
				type: 'string',
				default: '',
			},
			{
				name: 'dunningAddressId',
				displayName: 'Dunning Address ID',
				description: 'ID of the dunning address',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'dunningEmailAddressesId',
				displayName: 'Dunning Email Addresses ID',
				description: 'ID of the dunning email addresses',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'enableDropshippingInNewSupplySources',
				displayName: 'Enable Dropshipping In New Supply Sources',
				description: 'Whether to enable dropshipping in new supply sources',
				type: 'boolean',
				default: false,
			},
			{
				name: 'eoriNumber',
				displayName: 'EORI Number',
				description: 'EORI number of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
			},
			{
				name: 'factoring',
				displayName: 'Factoring',
				description: 'Whether factoring is enabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'fixPhone2',
				displayName: 'Fixed Phone 2',
				description: 'Second fixed phone number of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
			},
			{
				name: 'fixedResponsibleUser',
				displayName: 'Fixed Responsible User',
				description: 'Whether the responsible user is fixed',
				type: 'boolean',
				default: false,
			},
			{
				name: 'formerSalesPartner',
				displayName: 'Former Sales Partner',
				description: 'Whether the party is a former sales partner',
				type: 'boolean',
				default: false,
			},
			{
				name: 'habitualExporter',
				displayName: 'Habitual Exporter',
				description: 'Whether the party is a habitual exporter',
				type: 'boolean',
				default: false,
			},
			{
				name: 'imageId',
				displayName: 'Image ID',
				description: 'ID of the image of the party',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'invoiceBlock',
				displayName: 'Invoice Block',
				description: 'Whether the party has an invoice block',
				type: 'boolean',
				default: false,
			},
			{
				name: 'invoiceRecipientId',
				displayName: 'Invoice Recipient ID',
				description: 'ID of the invoice recipient',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'leadRatingId',
				displayName: 'Lead Rating ID',
				description: 'ID of the lead rating',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'leadSourceId',
				displayName: 'Lead Source ID',
				description: 'ID of the lead source',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'leadStatus',
				displayName: 'Lead Status',
				description: 'Lead status of the party',
				type: 'options',
				default: '',
				options: [
					{
						name: 'Converted',
						value: 'CONVERTED',
					},
					{
						name: 'Disqualified',
						value: 'DISQUALIFIED',
					},
					{
						name: 'New',
						value: 'NEW',
					},
					{
						name: 'Prequalified',
						value: 'PREQUALIFIED',
					},
					{
						name: 'Qualified',
						value: 'QUALIFIED',
					},
				],
			},
			{
				name: 'legalFormId',
				displayName: 'Legal Form ID',
				description: 'ID of the legal form of the party',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'mobilePhone2',
				displayName: 'Mobile Phone 2',
				description: 'Second mobile phone number of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
			},
			{
				name: 'optInEmail',
				displayName: 'Opt In Email',
				description: 'Whether the party opted in to email communication',
				type: 'boolean',
				default: false,
			},
			{
				name: 'optInLetter',
				displayName: 'Opt In Letter',
				description: 'Whether the party opted in to letter communication',
				type: 'boolean',
				default: false,
			},
			{
				name: 'optInPhone',
				displayName: 'Opt In Phone',
				description: 'Whether the party opted in to phone communication',
				type: 'boolean',
				default: false,
			},
			{
				name: 'optInSms',
				displayName: 'Opt In SMS',
				description: 'Whether the party opted in to SMS communication',
				type: 'boolean',
				default: false,
			},
			{
				name: 'parentPartyId',
				displayName: 'Parent Party ID',
				description: 'ID of the parent party',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'contacts',
				displayName: 'Contacts',
				description: 'Contacts as a JSON array',
				type: 'json',
				default: '[]',
				placeholder: '[{}]',
			},
			{
				name: 'partyEmailAddresses',
				displayName: 'Party Email Addresses',
				description: 'Party email addresses as a JSON array',
				type: 'json',
				default: '[]',
				placeholder: '[{"toAddresses":"sales@example.com"}]',
			},
			{
				name: 'partyHabitualExporterLettersOfIntent',
				displayName: 'Party Habitual Exporter Letters Of Intent',
				description: 'Habitual exporter letters of intent as a JSON array',
				type: 'json',
				default: '[]',
				placeholder:
					'[{"automaticallySuggestInInvoice":true,"date":1735689600000,"type":"SINGLE_ACCOUNTING_EVENT"}]',
			},
			{
				name: 'phoneHome',
				displayName: 'Phone Home',
				description: 'Home phone number of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
			},
			{
				name: 'primaryContactId',
				displayName: 'Primary Contact ID',
				description: 'ID of the primary contact',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'purchaseEmailAddressesId',
				displayName: 'Purchase Email Addresses ID',
				description: 'ID of the purchase email addresses',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'purchaseViaPlafond',
				displayName: 'Purchase Via Plafond',
				description: 'Whether purchase via plafond is enabled',
				type: 'boolean',
				default: false,
			},
			{
				name: 'quotationEmailAddressesId',
				displayName: 'Quotation Email Addresses ID',
				description: 'ID of the quotation email addresses',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'ratingId',
				displayName: 'Rating ID',
				description: 'ID of the rating',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'referenceNumber',
				displayName: 'Reference Number',
				description: 'Reference number of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
			},
			{
				name: 'responsibleUserId',
				displayName: 'Responsible User ID',
				description: 'ID of the responsible user',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'salesInvoiceEmailAddressesId',
				displayName: 'Sales Invoice Email Addresses ID',
				description: 'ID of the sales invoice email addresses',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'salesOrderEmailAddressesId',
				displayName: 'Sales Order Email Addresses ID',
				description: 'ID of the sales order email addresses',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'salesPartner',
				displayName: 'Sales Partner',
				description: 'Whether the party is a sales partner',
				type: 'boolean',
				default: false,
			},
			{
				name: 'salesPartnerDefaultCommissionFix',
				displayName: 'Sales Partner Default Commission Fix',
				description: 'Default fixed commission for the sales partner',
				type: 'number',
				default: 0,
			},
			{
				name: 'salesPartnerDefaultCommissionPercentage',
				displayName: 'Sales Partner Default Commission Percentage',
				description: 'Default commission percentage for the sales partner',
				type: 'number',
				default: 0,
			},
			{
				name: 'salesPartnerDefaultCommissionType',
				displayName: 'Sales Partner Default Commission Type',
				description: 'Default commission type for the sales partner',
				type: 'options',
				default: '',
				options: [
					{
						name: 'Fix',
						value: 'FIX',
					},
					{
						name: 'Fix and Margin',
						value: 'FIX_AND_MARGIN',
					},
					{
						name: 'Fix and Revenue',
						value: 'FIX_AND_REVENUE',
					},
					{
						name: 'Margin',
						value: 'MARGIN',
					},
					{
						name: 'No Commission',
						value: 'NO_COMMISSION',
					},
					{
						name: 'Revenue',
						value: 'REVENUE',
					},
				],
			},
			{
				name: 'sectorId',
				displayName: 'Sector ID',
				description: 'ID of the sector of the party',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'supplier',
				displayName: 'Supplier',
				description: 'Whether the party is a supplier',
				type: 'boolean',
				default: false,
			},
			{
				name: 'supplierActive',
				displayName: 'Supplier Active',
				description: 'Whether the supplier is active',
				type: 'boolean',
				default: false,
			},
			{
				name: 'supplierCreditorAccountId',
				displayName: 'Supplier Creditor Account ID',
				description: 'ID of the creditor account of the supplier',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'supplierCreditorAccountingCodeId',
				displayName: 'Supplier Creditor Accounting Code ID',
				description: 'ID of the creditor accounting code of the supplier',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'supplierCustomerNumberAtSupplier',
				displayName: 'Supplier Customer Number At Supplier',
				description: 'Customer number at the supplier',
				type: 'string',
				typeOptions: {
					maxLength: 64,
				},
				default: '',
			},
			{
				name: 'supplierDefaultShippingCarrierId',
				displayName: 'Supplier Default Shipping Carrier ID',
				description: 'ID of the default shipping carrier of the supplier',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'supplierInternalNote',
				displayName: 'Supplier Internal Note',
				description: 'Internal note of the supplier',
				type: 'string',
				default: '',
			},
			{
				name: 'supplierMergeItemsForOcrInvoiceUpload',
				displayName: 'Supplier Merge Items For OCR Invoice Upload',
				description: 'Whether to merge items for OCR invoice upload',
				type: 'boolean',
				default: false,
			},
			{
				name: 'supplierMinimumPurchaseOrderAmount',
				displayName: 'Supplier Minimum Purchase Order Amount',
				description: 'Minimum purchase order amount of the supplier',
				type: 'number',
				default: 0,
			},
			{
				name: 'supplierNonStandardTaxId',
				displayName: 'Supplier Non Standard Tax ID',
				description: 'ID of the non-standard tax of the supplier',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'supplierNumber',
				displayName: 'Supplier Number',
				description: 'Number of the supplier',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
			},
			{
				name: 'supplierNumberOld',
				displayName: 'Supplier Number Old',
				description: 'Old number of the supplier',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
			},
			{
				name: 'supplierOrderBlock',
				displayName: 'Supplier Order Block',
				description: 'Whether the supplier has an order block',
				type: 'boolean',
				default: false,
			},
			{
				name: 'supplierPaymentMethodId',
				displayName: 'Supplier Payment Method ID',
				description: 'ID of the payment method of the supplier',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'supplierShipmentMethodId',
				displayName: 'Supplier Shipment Method ID',
				description: 'ID of the shipment method of the supplier',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'supplierTermOfPaymentId',
				displayName: 'Supplier Term Of Payment ID',
				description: 'ID of the term of payment of the supplier',
				type: 'string',
				default: '',
				placeholder: '12345',
			},
			{
				name: 'taxId',
				displayName: 'Tax ID',
				description: 'Tax ID of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
			},
			{
				name: 'topics',
				displayName: 'Topics',
				description: 'Topics as a JSON array',
				type: 'json',
				default: '[]',
				placeholder: '[{}]',
			},
			{
				name: 'vatIdentificationNumber',
				displayName: 'VAT Identification Number',
				description: 'VAT identification number of the party',
				type: 'string',
				typeOptions: {
					maxLength: 1000,
				},
				default: '',
			},
			{
				name: 'xRechnungLeitwegId',
				displayName: 'XRechnung Leitweg ID',
				description: 'XRechnung Leitweg ID of the party',
				type: 'string',
				typeOptions: {
					maxLength: 46,
				},
				default: '',
			},
		],
	},
];

const displayOptions = {
	show: {
		resource: ['party'],
		operation: ['create'],
	},
};

export const description = updateDisplayOptions(displayOptions, properties);
