name: 🔄 Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml

  workflow_dispatch:

permissions:
  issues: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 🔄 Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v7

      - name: 🏷️ Sync labels
        uses: srealmoreno/label-sync-action@v2.0.0
        with:
          clean-labels: true
